class LibrarySystem{
constructor(){this.categories=["watchlist","watched","favorites","recommendations"];this.initializeLibrary();}
initializeLibrary(){this.setupEventListeners();document.addEventListener("userLoggedIn",()=>this.loadLibrary());document.addEventListener("userLoggedOut",()=>this.clearLibrary());}
setupEventListeners(){document.querySelectorAll(".tab-btn").forEach(btn=>{btn.addEventListener("click",(e)=>{document.querySelectorAll(".tab-btn").forEach(b=>b.classList.remove("active"));e.currentTarget.classList.add("active");this.showCategory(e.currentTarget.dataset.tab);});});}
loadLibrary(){if(!window.currentUser)return;const saved=localStorage.getItem(`library_${window.currentUser.ticket}`);this.userLibrary=saved?JSON.parse(saved):this.createDefaultLibrary();this.updateUI();}
createDefaultLibrary(){const lib={};this.categories.forEach(cat=>lib[cat]=[]);lib.stats={movies:0,series:0,anime:0};return lib;}
saveLibrary(){if(window.currentUser){localStorage.setItem(`library_${window.currentUser.ticket}`,JSON.stringify(this.userLibrary));}}
addItem(content,category="watchlist"){if(!window.currentUser||!this.categories.includes(category))return false;const exists=this.userLibrary[category].some(item=>item.id===content.id&&item.type===content.type);if(!exists){this.userLibrary[category].unshift({...content,addedAt:new Date().toISOString()});this.updateStats(content.type);this.saveLibrary();this.updateUI();document.getElementById("globalNotification").textContent=`Añadido a ${this.getCategoryTitle(category)}`;document.getElementById("globalNotification").style.display="block";setTimeout(()=>{document.getElementById("globalNotification").style.display="none";},2000);return true;}return false;}
removeItem(contentId,contentType,category){if(!window.currentUser)return false;const index=this.userLibrary[category].findIndex(item=>item.id===contentId&&item.type===contentType);if(index>-1){this.userLibrary[category].splice(index,1);this.saveLibrary();this.updateUI();return true;}return false;}
updateStats(type){const stats=this.userLibrary.stats;switch(type){case"movie":stats.movies++;break;case"tv":stats.series++;break;case"anime":stats.anime++;break;}this.saveLibrary();}
showCategory(category){if(!window.currentUser){authSystem.showLogin();return;}const container=document.getElementById("libraryContent");if(!container)return;const items=this.userLibrary[category]||[];if(items.length===0){container.innerHTML=`<div class="empty-state"><i class="fas fa-${this.getCategoryIcon(category)}"></i><h3>${this.getCategoryTitle(category)}</h3><p>${this.getCategoryDescription(category)}</p></div>`;return;}container.innerHTML=items.map(item=>this.createLibraryCard(item,category)).join("");container.querySelectorAll(".library-card").forEach(card=>{card.addEventListener("click",()=>{const id=card.dataset.id;const type=card.dataset.type;window.showDetails(id,type);});});}
createLibraryCard(item,category){const image=item.poster_path?`${TMDB_CONFIG.image_base}/w185${item.poster_path}`:item.images?.jpg?.image_url||"https://via.placeholder.com/185x278";const title=item.title||item.name||item.title_english;return`<div class="library-card content-card" data-id="${item.id}" data-type="${item.type}"><img src="${image}" alt="${title}" class="card-image"><div class="card-info"><h4>${title}</h4><div class="card-meta"><span>${new Date(item.addedAt).toLocaleDateString()}</span></div></div></div>`;}
getCategoryIcon(category){const icons={watchlist:"clock",watched:"eye",favorites:"heart",recommendations:"star"};return icons[category]||"folder";}
getCategoryTitle(category){const titles={watchlist:"Por Ver",watched:"Vistos",favorites:"Favoritos",recommendations:"Recomendados"};return titles[category]||"Categoría";}
getCategoryDescription(category){const desc={watchlist:"Contenido que planeas ver más tarde",watched:"Contenido que ya has visto",favorites:"Tu contenido favorito",recommendations:"Recomendaciones para ti"};return desc[category]||"";}
updateUI(){if(!window.currentUser)return;document.getElementById("statMovies").textContent=this.userLibrary.stats.movies;document.getElementById("statSeries").textContent=this.userLibrary.stats.series;document.getElementById("statAnime").textContent=this.userLibrary.stats.anime;this.categories.forEach(category=>{const count=this.userLibrary[category].length;const btn=document.querySelector(`.tab-btn[data-tab="${category}"]`);if(btn){let badge=btn.querySelector(".tab-badge");if(!badge){badge=document.createElement("span");badge.className="tab-badge";btn.appendChild(badge);}badge.textContent=count;}});}
clearLibrary(){this.userLibrary=null;document.querySelectorAll(".tab-badge").forEach(badge=>badge.remove());const container=document.getElementById("libraryContent");if(container)container.innerHTML=`<div class="empty-state"><i class="fas fa-sign-in-alt"></i><h3>Inicia sesión</h3><p>Para acceder a tu biblioteca</p></div>`;}}
window.librarySystem=new LibrarySystem();