class ProfileSystem{
constructor(){this.initializeProfile();}
initializeProfile(){this.setupEventListeners();document.addEventListener("userLoggedIn",()=>this.loadProfile());document.addEventListener("userLoggedOut",()=>this.clearProfile());}
setupEventListeners(){document.getElementById("profileForm")?.addEventListener("submit",(e)=>{e.preventDefault();this.saveProfile();});document.querySelector(".avatar-edit")?.addEventListener("click",()=>this.editAvatar());}
loadProfile(){if(!window.currentUser)return;const savedProfile=localStorage.getItem(`profile_${window.currentUser.ticket}`);if(savedProfile){const profile=JSON.parse(savedProfile);document.getElementById("profileName").value=profile.name||"";document.getElementById("profileEmail").value=profile.email||"";document.getElementById("profileLanguage").value=profile.language||"es-ES";document.getElementById("profileRegion").value=profile.region||"ES";}}
saveProfile(){if(!window.currentUser)return;const name=document.getElementById("profileName").value.trim();const email=document.getElementById("profileEmail").value.trim();const language=document.getElementById("profileLanguage").value;const region=document.getElementById("profileRegion").value;if(!name||!email){this.showMessage("Nombre y email requeridos","error");return;}const profile={name,email,language,region,updatedAt:new Date().toISOString()};localStorage.setItem(`profile_${window.currentUser.ticket}`,JSON.stringify(profile));document.getElementById("userName").textContent=name;document.getElementById("profileDisplayName").textContent=name;this.showMessage("Perfil actualizado","success");}
editAvatar(){const input=document.createElement("input");input.type="file";input.accept="image/*";input.onchange=(e)=>{const file=e.target.files[0];if(file){this.uploadAvatar(file);}};input.click();}
uploadAvatar(file){const reader=new FileReader();reader.onload=(e)=>{const avatar=e.target.result;localStorage.setItem(`avatar_${window.currentUser.ticket}`,avatar);this.showMessage("Avatar actualizado","success");};reader.readAsDataURL(file);}
clearProfile(){document.getElementById("profileName").value="";document.getElementById("profileEmail").value="";document.getElementById("profileLanguage").value="es-ES";document.getElementById("profileRegion").value="ES";}
showMessage(message,type="info"){const notification=document.getElementById("globalNotification");notification.textContent=message;notification.style.background=type==="success"?"var(--success)":type==="error"?"var(--accent)":"var(--primary)";notification.style.display="block";setTimeout(()=>{notification.style.display="none";},3000);}}
window.profileSystem=new ProfileSystem();